#---------------------------------------------------------------------------------------------#
#Purpose:
#    to parse through the result-files and the qgram-files generated by 'probe-generator'
#    in order to find sequences in q-gram-files which do not appear in the match-list (between pattern and genome) generated by 'probe-generator'
#---------------------------------------------------------------------------------------------#

import os
import re
from dircache import listdir

#Create artificial q-gram-list listing all probes of length n from a particular virus segment
qgramindexlist = range(0, 1000)

if __name__=="__main__":
    
    #get a list of all files in the current working directory of python
    resultfiles = listdir(os.getcwd())

    for resultfile in resultfiles:
        #consider only those files which end in ".result"
        if not resultfile.endswith(".result"): continue
        #open each file as "read only"
        with open(resultfile, "r") as f:
            
            for line in f:
                #in each file and each line get a list of first words only (e.g. "read_045"
                firstword = line.split()[0]
                #extract only numbers for the list of all first words
                matchingindex = int(re.findall(r'\d+', firstword)[0])
                #remove all numbers from the q-gram-index, leaving only those sequences for which raszers did not return a match between virus and host-genome
                qgramindexlist.remove(matchingindex)

    print qgramindexlist
    print len(qgramindexlist)
    
    